function SYN_params = SYN_params_default(do_syn)
n_classes = 3;
IHCs_per_channel = 10;
% Parameters could generally have columns if class-dependent.
SYN_params = struct( ...
  'do_syn', do_syn, ...  % This may just turn it off completely.
  'n_classes', n_classes, ...
  'healthy_n_fibers', [50, 35, 25] * IHCs_per_channel, ...
  'spont_rates', [50, 6, 1], ...  % Tweak last to 50, 5, 0.5 maybe?
  'sat_rates', 200, ...
  'sat_reservoir', 0.2, ...
  'v_width', 0.02, ...  % Mayb 0.025 tweak is better?
  'tau_lpf', 0.000080, ...
  'reservoir_tau', 0.020, ...
  'agc_weights', [1.2, 1.2, 1.2] / (22050*IHCs_per_channel));  % Tweaked.
  % The weights 1.2 were picked before correctly account for sample rate
  % and number of fibers.  This way works for more different numbers.
